
# This is an appspec.yml template file for use with an EC2/On-Premises deployment in CodeDeploy
version: 0.0
os: linux
files:
  - source: /build
    destination: /var/www/html
  - source: /config/nginx/
    destination: /etc/nginx
  - source: /config/cloudwatch/
    destination: /
file_exists_behavior: OVERWRITE
permissions:
  - object: /var/www/html
    pattern: "*"
    mode: 755
    owner: ubuntu
    group: ubuntu
    type:
      - directory
  - object: /var/www/html/
    mode: 755
    owner: ubuntu
    group: ubuntu
    type:
      - file
  # - object: /
  #   mode: 755
  #   owner: ubuntu
  #   group: ubuntu
  #   type:
  #     - directory
hooks:
  AfterInstall:
    - location: scripts/install_dependencies
      timeout: 600
      runas: ubuntu
  ApplicationStart:
    - location: scripts/setup-cloudwatch-agent
      timeout: 600
      runas: ubuntu 