version: 0.2


phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - npm i --force
      # - npm run lint

  build:
    commands:
      - npm run build

artifacts:
  files:
    - appspec.yml
    - build/**/*
    - scripts/**/*
    - config/**/*

